apiVersion: apps/v1
kind: Deployment
metadata:
  name: charpai-frontend
  namespace: dev-charp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charpai-frontend
  template:
    metadata:
      labels:
        app: charpai-frontend
    spec:
      containers:
        - name: charpai-frontend
          image: 390844737706.dkr.ecr.ap-south-1.amazonaws.com/charpai-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            # REQUIRED ENVIRONMENT VARIABLES
            - name: NEXT_PUBLIC_MAIN_URL
              value: "https://platform.whilter.ai" 
            - name: NEXT_PUBLIC_MEDIA_TOOLS_URL
              value: "http://localhost:3001" 
            - name: NEXT_PUBLIC_CHARP_AI_URL
              value: "http://localhost:3002"
            - name: NEXT_PUBLIC_MARKETPLACE_URL
              value: "http://localhost:3003" 
            - name: NEXT_PUBLIC_APP_AUTH_URL
              value: "https://manage.whilter.ai/api/user" 
            - name: NEXTAUTH_SECRET
              value: "LOUk8pQNkLUKmiLetuCsmEW/rHSHbUQt/BtpKSsj4/0="
            - name: NEXTAUTH_URL
              value: "https://platform.whilter.ai" 
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              value: "410778494117-294nk8cb53hf4bh64b773s3tjbs2tb1p.apps.googleusercontent.com"
            - name: NEXT_PUBLIC_RSA_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvz62jRMBT6Wh4CRjCtLwdXjTs8CTLyWt1E8IlH0u95s56ARU3F0hNZlQszN+wyoKbKj5AlGjxxAFHUyIKGLQPTW+mO6IA/ed0XPne6Q0Vj1KktqcdXfFKwNH87Mt8jKnbaF1BBUA3QNJgiGwC6BUsdijSpUFkahYNEitZxCVVf8w504KabNAeGNQbNXjiDr4UTSbGwBVpK/aMKENeqrVBATrk6hP9rfUt4EWzCDg2s8H4jAtzTAM1tMWXSuiHc9+BZIxcW4g2mA89z5MV2xeZvdV25VIts7kNfeq3/JttKS2FC9uWVhsxTXYkWt0J8XBbVGD1bHmM2iRsOWtH9//fQIDAQAB"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      