
export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  GUEST_GOOGLE = 'GUEST_GOOGLE',
  ADMIN = 'ADMIN',
  CAMPAIGN_MANAGER = 'CAMPAIGN_MANAGER',
  CREATIVE_CONTRIBUTOR = 'CREATIVE_CONTRIBUTOR',
  CREATIVE_EDITOR="CREATIVE_EDITOR"
}

export const SECTIONS = {
  DASHBOARD: 'DASHBOARD',
  MEDIA_TOOLS: 'MEDIA_TOOLS',
  CHARP_AI: 'CHARP_AI',
  MARKETPLACE: 'MARKETPLACE'
} as const;

export type Section = (typeof SECTIONS)[keyof typeof SECTIONS];
