apiVersion: v1
kind: Service
metadata:
  name: whilter-platform-frontend-service
  namespace: dev-charp
spec:
  selector:
    app: whilter-platform-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP