
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whilter-media-tools-frontend
  namespace: dev-charp
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:390844737706:certificate/9dfd0593-5006-4d94-a15b-b7e5fb3b0bfb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
spec:
  ingressClassName: alb
  rules:
    - host: media-tools.whilter.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whilter-media-tools-frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - media-tools.whilter.ai

