apiVersion: apps/v1
kind: Deployment
metadata:
  name: whilter-charpai-frontend
  namespace: dev-charp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whilter-charpai-frontend
  template:
    metadata:
      labels:
        app: whilter-charpai-frontend
    spec:
      containers:
        - name: whilter-charpai-frontend
          image: 390844737706.dkr.ecr.ap-south-1.amazonaws.com/whilter-charpai-frontend:1.1
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXTAUTH_SECRET
              value: "LOUk8pQNkLUKmiLetuCsmEW/rHSHbUQt/BtpKSsj4/0="
            - name: NEXTAUTH_URL
              value: "https://charp-ai.whilter.ai" 
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
              
      