import { MainLayout } from "@whilter/shared-layouts/main";
import { ThemeConfig } from "@whilter/config";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeConfig>
          <MainLayout>
            {children}
          </MainLayout>
        </ThemeConfig></body>
    </html>
  )
}
